/* Generated By:JavaCC: Do not edit this line. RewParser.java */
package it.disim.univaq.sealab.ttep.rew;

public class RewParser implements RewParserConstants {
  public static void main(String args []) throws ParseException
  {
    RewParser parser;
                if (args.length == 1) {
      System.out.println("Rew Parser Version 1.0:  Reading from file " + args[0] + " . . .");
      try {
        parser = new RewParser(new java.io.FileInputStream(args[0]));
      }
      catch (java.io.FileNotFoundException e) {
        System.out.println("Rew Parser Version 1.0:  File " + args[0] + " not found.");
        return;
      }
    }
    else {
      System.out.println("Rew Parser Version 1.0:  Usage is one of:");
      System.out.println("         java RewParser < inputfile");
      System.out.println("OR");
      System.out.println("         java RewParser inputfile");
      return;
    }
    try {
      parser.RewSpec();
      System.out.println("Rew Parser Version 1.0:  Ruby program parsed successfully.");
    }
    catch (ParseException e) {
      System.out.println(e.getMessage());
      System.out.println("Rew Parser Version 1.0:  Encountered errors during parse.");
    }

  }

/*
 * Expression syntax follows.
 */
  final public specificheAEmilia.IdentExpr IdentExpr() throws ParseException {
        specificheAEmilia.IdentExpr ris;
        Token t;
    t = jj_consume_token(T_ID);
                ris = new specificheAEmilia.IdentExpr(t.image);
                {if (true) return ris;}
    throw new Error("Missing return statement in function");
  }

  final public specificheAEmilia.Expression Erecord() throws ParseException {
        specificheAEmilia.Expression ris;
        java.util.List<specificheAEmilia.Expression> list = new java.util.ArrayList<specificheAEmilia.Expression>();
        specificheAEmilia.Expression expression;
        specificheAEmilia.IdentExpr identExpr;
        Token t1;
        Token t2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case T_RECORD_CONS:
      jj_consume_token(T_RECORD_CONS);
      jj_consume_token(LPAREN);
      expression = E();
                                                   list.add(expression);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        jj_consume_token(COMMA);
        expression = E();
                                                                                                     list.add(expression);
      }
      jj_consume_token(RPAREN);
                specificheAEmilia.Expression[] expressions = new specificheAEmilia.Expression[list.size()];
                for (int i = 0; i < list.size(); i++)
                        {
                        specificheAEmilia.Expression exp1 = list.get(i);
                        expressions[i] = exp1;
                        }
                specificheAEmilia.RecordCons recordCons = new specificheAEmilia.RecordCons(expressions);
                ris = recordCons;
                {if (true) return ris;}
      break;
    case T_PUT:
      jj_consume_token(T_PUT);
      jj_consume_token(LPAREN);
      t1 = jj_consume_token(T_ID);
      jj_consume_token(COMMA);
      expression = E();
      jj_consume_token(COMMA);
      identExpr = IdentExpr();
      jj_consume_token(RPAREN);
                specificheAEmilia.Put put = new specificheAEmilia.Put(t1.image,expression,identExpr);
                ris = put;
                {if (true) return ris;}
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public specificheAEmilia.Expression Earr() throws ParseException {
        java.util.List<specificheAEmilia.Expression> list = new java.util.ArrayList<specificheAEmilia.Expression>();
        specificheAEmilia.Expression expression;
        specificheAEmilia.Expression expression2;
        specificheAEmilia.IdentExpr identExpr;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case T_ARRAY_CONS:
      jj_consume_token(T_ARRAY_CONS);
      jj_consume_token(LPAREN);
      expression = E();
                                                  list.add(expression);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[2] = jj_gen;
          break label_2;
        }
        jj_consume_token(COMMA);
        expression = E();
                                                                                                    list.add(expression);
      }
      jj_consume_token(RPAREN);
                specificheAEmilia.Expression[] expressions = new specificheAEmilia.Expression[list.size()];
                for (int i = 0; i < list.size(); i++)
                        {
                        specificheAEmilia.Expression exp1 = list.get(i);
                        expressions[i] = exp1;
                        }
                specificheAEmilia.ArrayCons arrayCons = new specificheAEmilia.ArrayCons(expressions);
                {if (true) return arrayCons;}
      break;
    case T_WRITE:
      jj_consume_token(T_WRITE);
      jj_consume_token(LPAREN);
      expression = E();
      jj_consume_token(COMMA);
      expression2 = E();
      jj_consume_token(COMMA);
      identExpr = IdentExpr();
      jj_consume_token(RPAREN);
                specificheAEmilia.Write write = new specificheAEmilia.Write(expression,expression2,identExpr);
                {if (true) return write;}
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public specificheAEmilia.Expression El() throws ParseException {
        specificheAEmilia.Expression expression;
        java.util.List<specificheAEmilia.Expression> list = new java.util.ArrayList<specificheAEmilia.Expression>();
        Token t1;
        specificheAEmilia.IdentExpr identExpr;
        Token t2;
        specificheAEmilia.IdentExpr identExpr2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case T_LIST_CONS:
      jj_consume_token(T_LIST_CONS);
      jj_consume_token(LPAREN);
      if (jj_2_1(1)) {
        expression = E();
                                                  list.add(expression);
        label_3:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case COMMA:
            ;
            break;
          default:
            jj_la1[4] = jj_gen;
            break label_3;
          }
          jj_consume_token(COMMA);
          expression = E();
                                                                                                     list.add(expression);
        }
      } else {
        ;
      }
      jj_consume_token(RPAREN);
                specificheAEmilia.Expression[] expressions = new specificheAEmilia.Expression[list.size()];
                for (int i = 0; i < list.size(); i++)
                        {
                        specificheAEmilia.Expression exp1 = list.get(i);
                        expressions[i] = exp1;
                        }
                specificheAEmilia.ListCons listCons = new specificheAEmilia.ListCons(expressions);
                {if (true) return listCons;}
      break;
    case T_TAIL:
      jj_consume_token(T_TAIL);
      jj_consume_token(LPAREN);
      identExpr = IdentExpr();
      jj_consume_token(RPAREN);
                specificheAEmilia.Tail tail = new specificheAEmilia.Tail(identExpr);
                {if (true) return tail;}
      break;
    case T_CONCAT:
      jj_consume_token(T_CONCAT);
      jj_consume_token(LPAREN);
      identExpr = IdentExpr();
      jj_consume_token(COMMA);
      identExpr2 = IdentExpr();
      jj_consume_token(RPAREN);
                specificheAEmilia.Concat concat = new specificheAEmilia.Concat(identExpr,identExpr2);
                {if (true) return concat;}
      break;
    case T_INSERT:
      jj_consume_token(T_INSERT);
      jj_consume_token(LPAREN);
      expression = E();
      jj_consume_token(COMMA);
      identExpr = IdentExpr();
      jj_consume_token(RPAREN);
                specificheAEmilia.Insert insert = new specificheAEmilia.Insert(expression,identExpr);
                {if (true) return insert;}
      break;
    case T_REMOVE:
      jj_consume_token(T_REMOVE);
      jj_consume_token(LPAREN);
      expression = E();
      jj_consume_token(COMMA);
      identExpr = IdentExpr();
      jj_consume_token(RPAREN);
                specificheAEmilia.Remove remove = new specificheAEmilia.Remove(expression,identExpr);
                {if (true) return remove;}
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public specificheAEmilia.Expression Eatf() throws ParseException {
        specificheAEmilia.Expression ris;
        Token t1;
        specificheAEmilia.IdentExpr identExpr;
    if (jj_2_2(2147483647)) {
      jj_consume_token(LPAREN);
      ris = E();
      jj_consume_token(RPAREN);
                {if (true) return ris;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case T_ID:
        ris = IdentExpr();
                {if (true) return ris;}
        break;
      case T_NUMBER:
        t1 = jj_consume_token(T_NUMBER);
                try {
                        java.lang.Long number = java.lang.Long.parseLong(t1.image);
                        specificheAEmilia.Integer integer = new specificheAEmilia.Integer(number.intValue());
                        {if (true) return integer;}
                        }
                catch (NumberFormatException e1)
                        {
                        try {
                                java.lang.Double double1 = java.lang.Double.parseDouble(t1.image);
                                specificheAEmilia.Real real = new specificheAEmilia.Real(double1);
                                {if (true) return real;}
                                }
                        catch (NumberFormatException e2)
                                {
                                {if (true) return null;}
                                }
                        }
                {if (true) return null;}
        break;
      default:
        jj_la1[6] = jj_gen;
        if (jj_2_3(2147483647)) {
          jj_consume_token(T_LENGTH);
          jj_consume_token(LPAREN);
          identExpr = IdentExpr();
          jj_consume_token(RPAREN);
                specificheAEmilia.Length length = new specificheAEmilia.Length(identExpr);
                {if (true) return length;}
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public specificheAEmilia.Expression Eat() throws ParseException {
        specificheAEmilia.Expression e1;
        specificheAEmilia.Expression e2;
        java.util.List<specificheAEmilia.Expression> list = new java.util.ArrayList<specificheAEmilia.Expression>();
    e1 = Eatf();
                list.add(e1);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLICATION:
      case DIVISION:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_4;
      }
      if (jj_2_4(2147483647)) {
        jj_consume_token(MULTIPLICATION);
        e2 = Eatf();
                specificheAEmilia.Expression exp1 = list.get(list.size() - 1);
                specificheAEmilia.Moltiplicazione moltiplicazione = new specificheAEmilia.Moltiplicazione(exp1,e2);
                list.add(moltiplicazione);
      } else if (jj_2_5(2147483647)) {
        jj_consume_token(DIVISION);
        e2 = Eatf();
                specificheAEmilia.Expression exp2 = list.get(list.size() - 1);
                specificheAEmilia.Divisione divisione = new specificheAEmilia.Divisione(exp2,e2);
                list.add(divisione);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                specificheAEmilia.Expression exp3 = list.get(list.size() - 1);
                {if (true) return exp3;}
    throw new Error("Missing return statement in function");
  }

  final public specificheAEmilia.Expression Ea() throws ParseException {
        specificheAEmilia.Expression e1;
        specificheAEmilia.Expression e2;
        java.util.List<specificheAEmilia.Expression> list = new java.util.ArrayList<specificheAEmilia.Expression>();
    e1 = Eat();
                list.add(e1);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ADDITION:
      case SUBTRACTION:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_5;
      }
      if (jj_2_6(2147483647)) {
        jj_consume_token(ADDITION);
        e2 = Eat();
                specificheAEmilia.Expression exp1 = list.get(list.size() - 1);
                specificheAEmilia.Somma somma = new specificheAEmilia.Somma(exp1,e2);
                list.add(somma);
      } else if (jj_2_7(2147483647)) {
        jj_consume_token(SUBTRACTION);
        e2 = Eat();
                specificheAEmilia.Expression exp2 = list.get(list.size() - 1);
                specificheAEmilia.Sottrazione sottrazione = new specificheAEmilia.Sottrazione(exp2,e2);
                list.add(sottrazione);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                specificheAEmilia.Expression exp3 = list.get(list.size() - 1);
                {if (true) return exp3;}
    throw new Error("Missing return statement in function");
  }

  final public specificheAEmilia.Expression Ebt() throws ParseException {
        specificheAEmilia.Expression e1;
        specificheAEmilia.Expression e2;
        Token t1;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case T_TRUE:
      t1 = jj_consume_token(T_TRUE);
                specificheAEmilia.Boolean b1 = new specificheAEmilia.Boolean(true);
                {if (true) return b1;}
      break;
    case T_FALSE:
      t1 = jj_consume_token(T_FALSE);
                specificheAEmilia.Boolean b2 = new specificheAEmilia.Boolean(false);
                {if (true) return b2;}
      break;
    default:
      jj_la1[9] = jj_gen;
      if (jj_2_8(2147483647)) {
        e1 = Ea();
        jj_consume_token(LESS);
        e2 = Ea();
                specificheAEmilia.Minore minore = new specificheAEmilia.Minore(e1,e2);
                {if (true) return minore;}
      } else if (jj_2_9(2147483647)) {
        e1 = Ea();
        jj_consume_token(LE);
        e2 = Ea();
                specificheAEmilia.MinoreUguale minoreUguale = new specificheAEmilia.MinoreUguale(e1,e2);
                {if (true) return minoreUguale;}
      } else if (jj_2_10(2147483647)) {
        e1 = Ea();
        jj_consume_token(GREATER);
        e2 = Ea();
                specificheAEmilia.Maggiore maggiore = new specificheAEmilia.Maggiore(e1,e2);
                {if (true) return maggiore;}
      } else if (jj_2_11(2147483647)) {
        e1 = Ea();
        jj_consume_token(GE);
        e2 = Ea();
                specificheAEmilia.MaggioreUguale maggioreUguale = new specificheAEmilia.MaggioreUguale(e1,e2);
                {if (true) return maggioreUguale;}
      } else if (jj_2_12(2147483647)) {
        e1 = Ea();
        jj_consume_token(EQUAL);
        e2 = Ea();
                specificheAEmilia.Equal equal = new specificheAEmilia.Equal(e1,e2);
                {if (true) return equal;}
      } else if (jj_2_13(2147483647)) {
        e1 = Ea();
        jj_consume_token(NE);
        e2 = Ea();
                specificheAEmilia.Different different = new specificheAEmilia.Different(e1,e2);
                {if (true) return different;}
      } else if (jj_2_14(2147483647)) {
        jj_consume_token(LPAREN);
        e1 = Eb();
        jj_consume_token(RPAREN);
                {if (true) return e1;}
      } else if (jj_2_15(2147483647)) {
        jj_consume_token(EXCLAMATION);
        e1 = Ebt();
                {if (true) return e1;}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public specificheAEmilia.Expression Eb() throws ParseException {
        specificheAEmilia.Expression e1;
        specificheAEmilia.Expression e2;
        java.util.List<specificheAEmilia.Expression> list = new java.util.ArrayList<specificheAEmilia.Expression>();
    e1 = Ebt();
                list.add(e1);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
      case OR:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_6;
      }
      if (jj_2_16(2147483647)) {
        jj_consume_token(AND);
        e2 = Ebt();
                specificheAEmilia.Expression exp1 = list.get(list.size() - 1);
                specificheAEmilia.And and = new specificheAEmilia.And(exp1,e2);
                list.add(and);
      } else if (jj_2_17(2147483647)) {
        jj_consume_token(OR);
        e2 = Ebt();
                specificheAEmilia.Expression exp2 = list.get(list.size() - 1);
                specificheAEmilia.Or or = new specificheAEmilia.Or(exp2,e2);
                list.add(or);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                specificheAEmilia.Expression exp3 = list.get(list.size() - 1);
                {if (true) return exp3;}
    throw new Error("Missing return statement in function");
  }

  final public specificheAEmilia.Expression E() throws ParseException {
        specificheAEmilia.Expression ris;
        specificheAEmilia.Expression expression;
        specificheAEmilia.IdentExpr identExpr;
        Token t1;
        Token t2;
    if (jj_2_18(2147483647) && (getToken(2).kind != LESS && getToken(2).kind != LE &&
                    getToken(2).kind != GREATER && getToken(2).kind != GE &&
                    getToken(2).kind != EQUAL && getToken(2).kind != NE)) {
      ris = Ea();
                {if (true) return ris;}
    } else if (jj_2_19(2147483647)) {
      ris = Eb();
                {if (true) return ris;}
    } else if (jj_2_20(2147483647)) {
      ris = El();
                {if (true) return ris;}
    } else if (jj_2_21(2147483647)) {
      ris = Earr();
                {if (true) return ris;}
    } else if (jj_2_22(2147483647)) {
      ris = Erecord();
                {if (true) return ris;}
    } else if (jj_2_23(2147483647)) {
      jj_consume_token(T_FIRST);
      jj_consume_token(LPAREN);
      identExpr = IdentExpr();
      jj_consume_token(RPAREN);
                ris = new specificheAEmilia.First(identExpr);
                {if (true) return ris;}
    } else if (jj_2_24(2147483647)) {
      jj_consume_token(T_READ);
      jj_consume_token(LPAREN);
      expression = E();
      jj_consume_token(COMMA);
      identExpr = IdentExpr();
      jj_consume_token(RPAREN);
                ris = new specificheAEmilia.Read(expression,identExpr);
                {if (true) return ris;}
    } else if (jj_2_25(2147483647)) {
      jj_consume_token(T_GET);
      jj_consume_token(LPAREN);
      t1 = jj_consume_token(T_ID);
      jj_consume_token(COMMA);
      identExpr = IdentExpr();
      jj_consume_token(RPAREN);
                ris = new specificheAEmilia.Get(t1.image,identExpr);
                {if (true) return ris;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public it.disim.univaq.sealab.ttep.rew.classes.RewardType RewardType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case T_STATE_REWARD:
      jj_consume_token(T_STATE_REWARD);
                {if (true) return it.disim.univaq.sealab.ttep.rew.classes.RewardType.STATE_REWARD;}
      break;
    case T_TRANS_REWARD:
      jj_consume_token(T_TRANS_REWARD);
                {if (true) return it.disim.univaq.sealab.ttep.rew.classes.RewardType.TRANS_REWARD;}
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public it.disim.univaq.sealab.ttep.rew.classes.RewardAssign RewardAssign() throws ParseException {
        Token t1;
        Token t2;
        Token t3;
        specificheAEmilia.Expression e1 = null;
        specificheAEmilia.Expression e2;
        specificheAEmilia.Expression e3 = null;
        it.disim.univaq.sealab.ttep.rew.classes.RewardType rewardType;
        specificheAEmilia.Expression e4;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case T_ENABLED:
      jj_consume_token(T_ENABLED);
      jj_consume_token(LPAREN);
      t1 = jj_consume_token(T_ID);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LBRACKET:
        jj_consume_token(LBRACKET);
        e1 = E();
        jj_consume_token(RBRACKET);
        break;
      default:
        jj_la1[12] = jj_gen;
        ;
      }
      jj_consume_token(DOT);
      t2 = jj_consume_token(T_ID);
      jj_consume_token(RPAREN);
      jj_consume_token(IMPL);
      rewardType = RewardType();
      jj_consume_token(LPAREN);
      e4 = E();
      jj_consume_token(RPAREN);
                it.disim.univaq.sealab.ttep.rew.classes.RewardAssign rewardAssign = new it.disim.univaq.sealab.ttep.rew.classes.RewardAssign(t2.image,e1,t1.image,rewardType,e4);
                {if (true) return rewardAssign;}
      break;
    case T_FOR_ALL:
      jj_consume_token(T_FOR_ALL);
      t1 = jj_consume_token(T_ID);
      jj_consume_token(T_IN);
      e1 = E();
      jj_consume_token(DOTDOT);
      e2 = E();
      jj_consume_token(T_ENABLED);
      jj_consume_token(LPAREN);
      t2 = jj_consume_token(T_ID);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LBRACKET:
        jj_consume_token(LBRACKET);
        e3 = E();
        jj_consume_token(RBRACKET);
        break;
      default:
        jj_la1[13] = jj_gen;
        ;
      }
      jj_consume_token(DOT);
      t3 = jj_consume_token(T_ID);
      jj_consume_token(RPAREN);
      jj_consume_token(IMPL);
      rewardType = RewardType();
      jj_consume_token(LPAREN);
      e4 = E();
      jj_consume_token(RPAREN);
                it.disim.univaq.sealab.ttep.rew.classes.RewardAssignInd rewardAssignInd = new it.disim.univaq.sealab.ttep.rew.classes.RewardAssignInd(t3.image,e3,t2.image,t1.image,e1,e2,rewardType,e4);
                {if (true) return rewardAssignInd;}
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public it.disim.univaq.sealab.ttep.rew.classes.RewardStructure RewardStructure() throws ParseException {
        java.util.List<it.disim.univaq.sealab.ttep.rew.classes.RewardAssign> list = new java.util.ArrayList<it.disim.univaq.sealab.ttep.rew.classes.RewardAssign>();
        it.disim.univaq.sealab.ttep.rew.classes.RewardAssign ra;
    label_7:
    while (true) {
      ra = RewardAssign();
                list.add(ra);
      if (jj_2_26(2)) {
        ;
      } else {
        break label_7;
      }
    }
                it.disim.univaq.sealab.ttep.rew.classes.RewardStructure rewardStructure = new it.disim.univaq.sealab.ttep.rew.classes.RewardStructure(list);
                {if (true) return rewardStructure;}
    throw new Error("Missing return statement in function");
  }

  final public it.disim.univaq.sealab.ttep.rew.classes.MeasureDef MeasureDef() throws ParseException {
        Token t1;
        Token t2;
        specificheAEmilia.Expression e1 = null;
        specificheAEmilia.Expression e2;
        specificheAEmilia.Expression e3 = null;
        it.disim.univaq.sealab.ttep.rew.classes.RewardStructure rs;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case T_MEASURE:
      jj_consume_token(T_MEASURE);
      t1 = jj_consume_token(T_ID);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LBRACKET:
        jj_consume_token(LBRACKET);
        e1 = E();
        jj_consume_token(RBRACKET);
        break;
      default:
        jj_la1[15] = jj_gen;
        ;
      }
      jj_consume_token(T_IS);
      rs = RewardStructure();
                it.disim.univaq.sealab.ttep.rew.classes.MeasureDef measureDef = new it.disim.univaq.sealab.ttep.rew.classes.MeasureDef(t1.image,e1,rs);
                {if (true) return measureDef;}
      break;
    case T_FOR_ALL:
      jj_consume_token(T_FOR_ALL);
      t1 = jj_consume_token(T_ID);
      jj_consume_token(T_IN);
      e1 = E();
      jj_consume_token(DOTDOT);
      e2 = E();
      jj_consume_token(T_MEASURE);
      t2 = jj_consume_token(T_ID);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LBRACKET:
        jj_consume_token(LBRACKET);
        e3 = E();
        jj_consume_token(RBRACKET);
        break;
      default:
        jj_la1[16] = jj_gen;
        ;
      }
      jj_consume_token(T_IS);
      rs = RewardStructure();
                it.disim.univaq.sealab.ttep.rew.classes.MeasureDefInd measureDefInd = new it.disim.univaq.sealab.ttep.rew.classes.MeasureDefInd(t2.image,e3,rs,t1.image,e1,e2);
                {if (true) return measureDefInd;}
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public it.disim.univaq.sealab.ttep.rew.classes.RewSpec RewSpec() throws ParseException {
        java.util.List<it.disim.univaq.sealab.ttep.rew.classes.MeasureDef> list = new java.util.ArrayList<it.disim.univaq.sealab.ttep.rew.classes.MeasureDef>();
        it.disim.univaq.sealab.ttep.rew.classes.MeasureDef md;
    md = MeasureDef();
                list.add(md);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEMICOLON:
        ;
        break;
      default:
        jj_la1[18] = jj_gen;
        break label_8;
      }
      jj_consume_token(SEMICOLON);
      md = MeasureDef();
                list.add(md);
    }
    jj_consume_token(0);
                it.disim.univaq.sealab.ttep.rew.classes.RewSpec rewSpec = new it.disim.univaq.sealab.ttep.rew.classes.RewSpec(list);
                {if (true) return rewSpec;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  private boolean jj_3R_12() {
    if (jj_3R_11()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_32()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3_18() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(T_LENGTH)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_9() {
    Token xsp;
    xsp = jj_scanpos;
    jj_lookingAhead = true;
    jj_semLA = getToken(2).kind != LESS && getToken(2).kind != LE &&
                getToken(2).kind != GREATER && getToken(2).kind != GE &&
                getToken(2).kind != EQUAL && getToken(2).kind != NE;
    jj_lookingAhead = false;
    if (!jj_semLA || jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_scan_token(T_LENGTH)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3_16() {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_scan_token(T_NUMBER)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_9()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) return true;
    }
    return false;
  }

  private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_9()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_3R_15()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_34()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_15() {
    if (jj_scan_token(EXCLAMATION)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_14()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(T_REMOVE)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_9()) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(EXCLAMATION)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(NE)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_9()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_64()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_scan_token(T_INSERT)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_9()) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_14()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(EQUAL)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(T_CONCAT)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(NE)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_scan_token(T_TAIL)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(GE)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(EQUAL)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(GREATER)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(GE)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_scan_token(T_LIST_CONS)) return true;
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_1()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(LE)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(GREATER)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3_26() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(LESS)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(LE)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(T_WRITE)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_9()) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_9()) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(LESS)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_scan_token(T_FOR_ALL)) return true;
    if (jj_scan_token(T_ID)) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(T_FALSE)) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_scan_token(T_ENABLED)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_19() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) return true;
    }
    return false;
  }

  private boolean jj_3R_17() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) return true;
    }
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_scan_token(T_ARRAY_CONS)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_9()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_62()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(T_TRUE)) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_scan_token(SUBTRACTION)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_scan_token(T_PUT)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(T_ID)) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_9()) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_scan_token(ADDITION)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_scan_token(SUBTRACTION)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3_25() {
    if (jj_scan_token(T_GET)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(T_ID)) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_18() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) return true;
    }
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(T_RECORD_CONS)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_9()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_63()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_24() {
    if (jj_scan_token(T_READ)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_9()) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(ADDITION)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) return true;
    }
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(T_GET)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(T_ID)) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_3R_12()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_33()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_23() {
    if (jj_scan_token(T_FIRST)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(T_READ)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_9()) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_22() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_scan_token(T_ID)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(DIVISION)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(T_FIRST)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_21() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(MULTIPLICATION)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3_20() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(DIVISION)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_scan_token(MULTIPLICATION)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) return true;
    }
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_3R_16()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public RewParserTokenManager token_source;
  JavaCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[19];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x4000,0x0,0x4000,0x0,0x4000,0x0,0x0,0x6000000,0x18000000,0x0,0x0,0x0,0x800,0x800,0x0,0x800,0x800,0x0,0x2000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x18000,0x0,0x6000,0x0,0x1f00,0x12000000,0x0,0x0,0xc,0x3,0xc00000,0x0,0x0,0x280000,0x0,0x0,0xa0000,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[26];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public RewParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public RewParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new RewParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public RewParser(java.io.Reader stream) {
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new RewParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public RewParser(RewParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(RewParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[67];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 19; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 67; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 26; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
