<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mapmeasurestoindices" nsURI="http://mapmeasurestoindices/1.0"
    nsPrefix="mapmeasurestoindices">
  <eClassifiers xsi:type="ecore:EClass" name="MeasureMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measureName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selector" eType="ecore:EClass ../../metamodel/model/mmAEmilia.ecore#//Expressions/Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//AeiMeasure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//ActionMeasure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="archiInteractions" upperBound="-1"
        eType="#//ArchiIntMeasure" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasureToArchiElemInstance" eSuperTypes="#//MeasureMapping"/>
  <eClassifiers xsi:type="ecore:EClass" name="MeasureToAction" eSuperTypes="#//MeasureMapping"/>
  <eClassifiers xsi:type="ecore:EClass" name="RewMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//MeasureMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IndexType">
    <eLiterals name="ResponseTime"/>
    <eLiterals name="Utilization" value="1"/>
    <eLiterals name="Throughput" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionMeasure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1" eType="#//IndexType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="ecore:EClass ../../metamodel/model/mmAEmilia.ecore#//Behavior/Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AeiMeasure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1" eType="#//IndexType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aei" lowerBound="1" eType="ecore:EClass ../../metamodel/model/mmAEmilia.ecore#//ArchiElemInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchiIntMeasure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1" eType="#//IndexType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="archiInteraction" lowerBound="1"
        eType="ecore:EClass ../../metamodel/model/mmAEmilia.ecore#//ArchitecturalInteraction"/>
  </eClassifiers>
</ecore:EPackage>
